# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Cisco-AccessList-Extended
version:      0.03
version_from: lib/Net/Cisco/AccessList/Extended.pm
installdirs:  site
requires:
    Class::Accessor:               0
    List::MoreUtils:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
